version: "2"
linters:
  enable:
    - errorlint
    - gocritic
    - misspell
    - nonamedreturns
  settings:
    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/mdelapenya)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
